// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var log;

  log = function(msg) {
    return console.log(msg);
  };

  describe("Self test", function() {
    return it("is ok", function() {
      return expect(true).toBe(true);
    });
  });

  describe("ModuleManager", function() {
    beforeEach(function() {
      return this.subject = new window.ModuleManager();
    });
    it('#version is 1.0.0', function() {
      return expect(this.subject.version).toEqual('1.0.0');
    });
    it('#name is ModuleManager', function() {
      return expect(this.subject.name).toEqual('ModuleManager');
    });
    return it('#_modules array of modules, empty at initialization', function() {
      return expect(this.subject._modules).toEqual([]);
    });
  });

}).call(this);
