// Generated by CoffeeScript 1.6.3
(function() {
  window.ModuleManager = (function() {
    ModuleManager.prototype.version = '1.0.0';

    ModuleManager.prototype.name = 'ModuleManager';

    ModuleManager.prototype._modules = [];

    function ModuleManager() {
      this._modules = [];
    }

    ModuleManager.prototype.add = function(module) {
      if (!this.isPresent(module.name)) {
        return this._modules.push(module);
      }
    };

    ModuleManager.prototype.isPresent = function(moduleName) {
      return this.get(moduleName) !== null;
    };

    ModuleManager.prototype.get = function(moduleName) {
      var m, _i, _len, _ref;
      _ref = this._modules;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        m = _ref[_i];
        if (m.name === moduleName) {
          return m;
        }
      }
      return null;
    };

    return ModuleManager;

  })();

}).call(this);
