// Generated by CoffeeScript 1.6.3
(function() {
  window.ModuleManager = (function() {
    ModuleManager.prototype.version = '1.0.0';

    ModuleManager.prototype.name = 'ModuleManager';

    ModuleManager.prototype._modules = [];

    function ModuleManager() {
      this._modules = [];
    }

    ModuleManager.prototype.add = function(module) {
      return this._modules.push(module);
    };

    return ModuleManager;

  })();

}).call(this);
